set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on
set -g update-environment "SSH_AUTH_SOCK SSH_CONNECTION DISPLAY SESSIONIZER_DIRS"

set -g escape-time 0
set -g focus-events on
set -g history-limit 50000
setw -g aggressive-resize on
set -g detach-on-destroy off

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind e source-file "$HOME/.config/tmux/tmux.conf"
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind -n M-H select-pane -L
bind -n M-J select-pane -D
bind -n M-K select-pane -U
bind -n M-L select-pane -R
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

bind -n M-h select-window -t -1
bind -n M-l select-window -t +1
bind j switch-client -p
bind k switch-client -n

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on
set -gw automatic-rename on
set -gw automatic-rename-format '#{b:pane_current_path}'

bind f run-shell "tmux neww ~/bin/tmux-sessionizer"
bind g display-popup -d '#{pane_current_path}' -xC -yC -w90% -h90% -E lazygit

set -g status-position top
set -g status-interval 5
set -g status-left-length 30
set -g status-right-length 50
set -g window-status-separator ""
set -g status-style "bg=default,fg=default"
set -g status-left "#[fg=black,bg=blue,bold] #S #[bg=default] "
set -g status-right "#[fg=blue]#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,}#[fg=brightblack]#h "
set -g window-status-format "#[fg=brightblack] #I:#{pane_current_command} "
set -g window-status-current-format "#[fg=blue,bold] #I:#{pane_current_command} "
set -g pane-border-style "fg=brightblack"
set -g pane-active-border-style "fg=blue"
set -g message-style "bg=default,fg=blue"
set -g mode-style "bg=blue,fg=black"
